INFLUX_TOKEN = "Lcbk6ZfZICYHBIlCqDCSM7hMyao0RnhzVZ4sPJZ_19pvxp9R2i2xZ6zRb2f2SBVLurbrPFO9yiMHJ_iTERON1w=="
INFLUX_URL = "http://localhost:8086"
INFLUX_ORG = "All the Best"
INFLUX_BUCKET = "STOCK_MARKET"
